import type { Node, Connection } from '../types';

export interface ConsoleLog {
  nodeId: string;
  nodeTitle: string;
  type: 'info' | 'success' | 'error' | 'warning';
  message: string;
  timestamp: string;
}

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

// Generate realistic mock search results
const getMockSearchResults = (query: string): string => {
  const topics = [
    { keys: ['react', 'vite'], title: 'Vite + React Integration Guide', snippet: 'Vite is a modern build tool that provides a faster development experience for React applications. It uses native ES modules to deliver instant hot module replacement (HMR).' },
    { keys: ['ai', 'agent', 'workflow'], title: 'Orchestrating Multi-Agent Systems', snippet: 'Multi-agent workflows enable sequential or parallel execution of autonomous LLM tasks. Using node-based structures, agents can search, reason, compile, and output structured templates.' },
    { keys: ['search', 'google'], title: 'Search Engine Retrieval APIs', snippet: 'Modern search APIs allow LLM workflows to fetch live web data. Integrating search results prevents hallucinations by grounding prompt context in real-time facts.' },
    { keys: ['cost', 'tokens'], title: 'LLM Token and Cost Optimization', snippet: 'Tracking input and output tokens is critical for scaling production AI workflows. Standard optimization models advise caching prompts and choosing smaller reasoning models for simple checks.' }
  ];

  const lowerQuery = query.toLowerCase();
  const matched = topics.filter(t => t.keys.some(k => lowerQuery.includes(k)));

  if (matched.length > 0) {
    return matched.map((m, i) => `[Result ${i + 1}] ${m.title}\nSource: ${m.snippet}`).join('\n\n');
  }

  return `[Search Results for "${query}"]\nFetched 3 pages.\nSummary: Found active discussions and documentations regarding ${query}. Visualizing connected developer nodes, API keys verify successfully, and setup compiles cleanly.`;
};

// Generate realistic mock LLM response based on prompt and inputs
const getMockLLMResponse = (prompt: string, inputs: Record<string, any>, model: string): string => {
  const modelPrefix = `[${model}]`;
  const inputsStr = Object.entries(inputs)
    .map(([k, v]) => `* ${k}: "${typeof v === 'object' ? JSON.stringify(v) : v}"`)
    .join('\n');

  if (prompt.toLowerCase().includes('sentiment')) {
    const textToAnalyze = inputs.input_text || inputs.text || '';
    const hasNegative = /sad|bad|error|fail|broken|worst|slow/i.test(String(textToAnalyze));
    const sentiment = hasNegative ? 'NEGATIVE' : 'POSITIVE';
    const confidence = hasNegative ? '89%' : '94%';
    return `Sentiment Analysis Report\nModel: ${model}\n\nAnalyzed Text: "${textToAnalyze}"\nDetected Sentiment: **${sentiment}** (Confidence: ${confidence})\n\nReasoning:\n- Key vocabulary words match standard emotional patterns.\n- Contextual tone is highly descriptive and indicator flags match ${sentiment.toLowerCase()} parameters.`;
  }

  if (prompt.toLowerCase().includes('lint') || prompt.toLowerCase().includes('refactor') || prompt.toLowerCase().includes('code')) {
    return `${modelPrefix} Code Analysis & Recommendation:\n\n1. **Optimization Suggestion**:\n   Found potential performance improvement by leveraging memoization and removing redundant side effects. Use CSS variables instead of inline styles.\n\n2. **Linting Check**:\n   - Clean compiles verified.\n   - Typings matches all interfaces.\n   - Avoid wildcard dependencies.\n\nRefactored Code Draft:\n\`\`\`javascript\n// Optimized Node Engine\nconst processFlowState = (nodes) => {\n  return nodes.map(n => ({...n, status: 'completed'}));\n};\n\`\`\``;
  }

  return `${modelPrefix} AI Agent Report\n------------------------\nPrompt Query: "${prompt.substring(0, 80)}${prompt.length > 80 ? '...' : ''}"\n\nInput Context:\n${inputsStr || 'No input variables provided.'}\n\nAnalysis & Output:\nThis is a high-fidelity synthetic report generated by ${model}. The flow orchestrator successfully passed all inputs downstream. System parameters look stable, rendering times are within 16ms boundaries, and connection vectors align perfectly.`;
};

// Execute custom JavaScript code block
const runJSCode = (code: string, inputs: Record<string, any>): any => {
  try {
    // Create safe sandbox function that takes inputs
    const run = new Function('inputs', `
      try {
        ${code}
      } catch (err) {
        return 'Execution error: ' + err.message;
      }
    `);
    return run(inputs);
  } catch (err: any) {
    return 'Compilation error: ' + err.message;
  }
};

export const executeWorkflow = async (
  nodes: Node[],
  connections: Connection[],
  geminiApiKey: string | null,
  onNodeStateChange: (nodeId: string, updates: Partial<Node['data']>) => void,
  onLog: (log: ConsoleLog) => void
) => {
  const startTime = Date.now();
  onLog({
    nodeId: 'system',
    nodeTitle: 'System Orchestrator',
    type: 'info',
    message: 'Starting workflow execution...',
    timestamp: new Date().toLocaleTimeString()
  });

  // Track executing state and outputs
  // Map of nodeId -> Map of outputPinName -> OutputValue
  const nodeOutputs: Record<string, Record<string, any>> = {};
  
  // Set of executed nodes
  const executedNodeIds = new Set<string>();
  
  // List of active queue
  let activeNodes = nodes.filter(n => {
    // Starting nodes: nodes with no incoming active connections
    const hasIncoming = connections.some(c => c.targetId === n.id);
    return !hasIncoming;
  });

  if (activeNodes.length === 0 && nodes.length > 0) {
    // Fallback if there are cycles or weird layouts, just start with input nodes or first nodes
    activeNodes = nodes.filter(n => n.type === 'input');
    if (activeNodes.length === 0) activeNodes = [nodes[0]];
  }

  let safetyCounter = 0;
  const maxIterations = 100;

  // Track details for history analytics
  let totalTokens = 0;

  while (activeNodes.length > 0 && safetyCounter++ < maxIterations) {
    // Run available nodes in parallel/sequence
    const nextQueue: Node[] = [];

    for (const node of activeNodes) {
      if (executedNodeIds.has(node.id)) continue;

      onNodeStateChange(node.id, { status: 'pending', error: undefined });
      onLog({
        nodeId: node.id,
        nodeTitle: node.title,
        type: 'info',
        message: `Executing node (Type: ${node.type})...`,
        timestamp: new Date().toLocaleTimeString()
      });

      const nodeRunStartTime = Date.now();
      let nodeError: string | undefined;
      let finalOutputs: Record<string, any> = {};

      try {
        // 1. Resolve inputs from upstream connections
        const resolvedInputs: Record<string, any> = {};
        for (const inputPin of node.inputs) {
          const incomingConn = connections.find(
            c => c.targetId === node.id && c.targetPin === inputPin.id
          );
          if (incomingConn) {
            const upstreamOutputs = nodeOutputs[incomingConn.sourceId];
            resolvedInputs[inputPin.name] = upstreamOutputs?.[incomingConn.sourcePin] ?? '';
          } else {
            resolvedInputs[inputPin.name] = '';
          }
        }

        // Wait a bit to simulate computational effort and allow visualization
        await sleep(1200);

        // 2. Perform the node task
        switch (node.type) {
          case 'input': {
            const val = node.data.inputValue || '';
            finalOutputs['output'] = val;
            onLog({
              nodeId: node.id,
              nodeTitle: node.title,
              type: 'success',
              message: `Received input text: "${val.substring(0, 40)}${val.length > 40 ? '...' : ''}"`,
              timestamp: new Date().toLocaleTimeString()
            });
            break;
          }

          case 'llm': {
            const model = node.data.model || 'gemini-1.5-flash';
            let template = node.data.promptTemplate || '';
            
            // Interpolate variables in prompt
            // Example template: "Write a blog post about {{topic}}"
            let prompt = template;
            Object.entries(resolvedInputs).forEach(([key, val]) => {
              prompt = prompt.replace(new RegExp(`\\{\\{\\s*${key}\\s*\\}\\}`, 'g'), String(val));
            });

            // Clean up any remaining unresolved variables
            prompt = prompt.replace(/\{\{\s*\w+\s*\}\}/g, '');

            let resultText = '';
            
            if (geminiApiKey) {
              onLog({
                nodeId: node.id,
                nodeTitle: node.title,
                type: 'info',
                message: `Sending prompt to Gemini API (${model})...`,
                timestamp: new Date().toLocaleTimeString()
              });
              
              try {
                const apiModelName = model === 'gemini-2.5-flash' ? 'gemini-2.5-flash' : 'gemini-1.5-flash';
                const url = `https://generativelanguage.googleapis.com/v1beta/models/${apiModelName}:generateContent?key=${geminiApiKey}`;
                
                const response = await fetch(url, {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json' },
                  body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: { temperature: node.data.temperature ?? 0.7 }
                  })
                });
                
                if (!response.ok) {
                  const errText = await response.text();
                  throw new Error(`Gemini API error: ${response.status} - ${errText}`);
                }
                
                const responseData = await response.json();
                resultText = responseData.candidates?.[0]?.content?.parts?.[0]?.text || '';
              } catch (apiErr: any) {
                onLog({
                  nodeId: node.id,
                  nodeTitle: node.title,
                  type: 'warning',
                  message: `API execution failed: ${apiErr.message}. Falling back to high-fidelity simulation.`,
                  timestamp: new Date().toLocaleTimeString()
                });
                resultText = getMockLLMResponse(prompt, resolvedInputs, model);
              }
            } else {
              resultText = getMockLLMResponse(prompt, resolvedInputs, model);
            }

            // Estimate tokens (roughly 1 token = 4 chars)
            const inputTokens = Math.ceil(prompt.length / 4);
            const outputTokens = Math.ceil(resultText.length / 4);
            totalTokens += (inputTokens + outputTokens);

            finalOutputs['response'] = resultText;
            onLog({
              nodeId: node.id,
              nodeTitle: node.title,
              type: 'success',
              message: `LLM execution complete. Generated response of length ${resultText.length} characters.`,
              timestamp: new Date().toLocaleTimeString()
            });
            break;
          }

          case 'search': {
            // Read query from inputs (if connected) or fall back to config
            const queryRaw = resolvedInputs['query'] || node.data.searchQuery || '';
            let searchResults = '';
            
            if (queryRaw) {
              onLog({
                nodeId: node.id,
                nodeTitle: node.title,
                type: 'info',
                message: `Searching web index for: "${queryRaw}"`,
                timestamp: new Date().toLocaleTimeString()
              });
              searchResults = getMockSearchResults(queryRaw);
            } else {
              searchResults = 'No query specified for search.';
            }

            finalOutputs['results'] = searchResults;
            onLog({
              nodeId: node.id,
              nodeTitle: node.title,
              type: 'success',
              message: `Web search completed successfully. Grounded context loaded.`,
              timestamp: new Date().toLocaleTimeString()
            });
            break;
          }

          case 'code': {
            const jsCode = node.data.code || 'return "";';
            onLog({
              nodeId: node.id,
              nodeTitle: node.title,
              type: 'info',
              message: 'Compiling and executing JavaScript sandbox...',
              timestamp: new Date().toLocaleTimeString()
            });

            const scriptResult = runJSCode(jsCode, resolvedInputs);
            
            finalOutputs['output'] = scriptResult;
            onLog({
              nodeId: node.id,
              nodeTitle: node.title,
              type: 'success',
              message: `JavaScript executed. Returned type: ${typeof scriptResult}`,
              timestamp: new Date().toLocaleTimeString()
            });
            break;
          }

          case 'condition': {
            const valToCheck = resolvedInputs['input_data'] || '';
            const op = node.data.conditionOperator || 'equals';
            const targetVal = node.data.conditionValue || '';
            let evaluation = false;

            switch (op) {
              case 'equals':
                evaluation = String(valToCheck).trim().toLowerCase() === String(targetVal).trim().toLowerCase();
                break;
              case 'contains':
                evaluation = String(valToCheck).toLowerCase().includes(String(targetVal).toLowerCase());
                break;
              case 'greater_than':
                evaluation = Number(valToCheck) > Number(targetVal);
                break;
              case 'less_than':
                evaluation = Number(valToCheck) < Number(targetVal);
                break;
            }

            // Route execution outputs
            // Condition node has 'true' and 'false' pins
            finalOutputs['true'] = evaluation ? valToCheck : null;
            finalOutputs['false'] = !evaluation ? valToCheck : null;

            onLog({
              nodeId: node.id,
              nodeTitle: node.title,
              type: 'success',
              message: `Conditional gate checked: [${valToCheck}] ${op} [${targetVal}] -> Result: ${evaluation.toString().toUpperCase()}`,
              timestamp: new Date().toLocaleTimeString()
            });
            break;
          }

          case 'output': {
            const value = resolvedInputs['input_data'] || '';
            finalOutputs['final_value'] = value;
            onLog({
              nodeId: node.id,
              nodeTitle: node.title,
              type: 'success',
              message: `Final workflow output gathered. Size: ${String(value).length} bytes.`,
              timestamp: new Date().toLocaleTimeString()
            });
            break;
          }
        }
      } catch (err: any) {
        nodeError = err.message || 'Unknown runtime error';
        onLog({
          nodeId: node.id,
          nodeTitle: node.title,
          type: 'error',
          message: `Node error: ${nodeError}`,
          timestamp: new Date().toLocaleTimeString()
        });
      }

      const duration = Date.now() - nodeRunStartTime;
      nodeOutputs[node.id] = finalOutputs;
      executedNodeIds.add(node.id);

      onNodeStateChange(node.id, {
        status: nodeError ? 'failed' : 'completed',
        error: nodeError,
        outputData: finalOutputs,
        executionTime: duration
      });
    }

    // Determine the next nodes to queue
    // A node is ready to queue if:
    // 1. It hasn't been executed yet.
    // 2. All of its connected inputs have upstream outputs available in nodeOutputs.
    // 3. Or, if it's connected to an output that is active (i.e. not null/skipped)
    for (const potentialNode of nodes) {
      if (executedNodeIds.has(potentialNode.id) || activeNodes.some(n => n.id === potentialNode.id)) {
        continue;
      }

      // Check if all active input connections are satisfied
      const incomingConnections = connections.filter(c => c.targetId === potentialNode.id);
      
      if (incomingConnections.length === 0) {
        continue; // Unconnected nodes can run in the first step or we skip them
      }

      let allInputsSatisfied = true;
      let pathIsSkipped = false;

      for (const conn of incomingConnections) {
        const upstreamExecuted = executedNodeIds.has(conn.sourceId);
        if (!upstreamExecuted) {
          allInputsSatisfied = false;
          break;
        }

        // Check if connection value is null (which means it was skipped by conditional logic)
        const sourceVal = nodeOutputs[conn.sourceId]?.[conn.sourcePin];
        if (sourceVal === null) {
          // Downstream connected node should be skipped as well
          pathIsSkipped = true;
        }
      }

      if (allInputsSatisfied) {
        if (pathIsSkipped) {
          // Automatically skip execution for this node
          executedNodeIds.add(potentialNode.id);
          onNodeStateChange(potentialNode.id, { status: 'idle', error: undefined, outputData: null });
          
          // Propagate skips by setting outputs to null
          const dummyOutputs: Record<string, any> = {};
          potentialNode.outputs.forEach(outPin => {
            dummyOutputs[outPin.id] = null;
          });
          nodeOutputs[potentialNode.id] = dummyOutputs;
          
          // Re-evaluate next nodes
          safetyCounter = 0; // reset safety count to allow propagation of skips
        } else {
          nextQueue.push(potentialNode);
        }
      }
    }

    activeNodes = nextQueue;
  }

  const duration = Date.now() - startTime;
  const executionFailed = nodes.some(n => n.data.status === 'failed');

  onLog({
    nodeId: 'system',
    nodeTitle: 'System Orchestrator',
    type: executionFailed ? 'error' : 'success',
    message: executionFailed 
      ? `Workflow failed. Total duration: ${duration}ms.`
      : `Workflow executed successfully! Total duration: ${duration}ms.`,
    timestamp: new Date().toLocaleTimeString()
  });

  return {
    success: !executionFailed,
    duration,
    tokens: totalTokens,
    nodesCount: executedNodeIds.size
  };
};
